/*
 * Projeto: GigAtende
 * Copyright (c) 2026 Raimundo Alves Santa Brigida
 *
 * Licensed under the PolyForm Noncommercial License 1.0.0.
 *
 * You may use, study, modify and redistribute this software.
 *
 * Commercial use, resale, sublicensing or inclusion in commercial
 * products or services is prohibited.
 *
 * Full license:
 * https://polyformproject.org/licenses/noncommercial/1.0.0/
 */
window.GigaEmojiData = [
  {
    id: 'smileys',
    name: 'Smileys e pessoas',
    icon: '😀',
    emojis: [
      { char: '😀', k: 'feliz sorriso rosto' },
      { char: '😃', k: 'feliz sorriso rosto olho aberto' },
      { char: '😄', k: 'feliz sorriso rosto olho fechado' },
      { char: '😁', k: 'feliz sorriso dentes' },
      { char: '😆', k: 'feliz sorriso rindo' },
      { char: '😅', k: 'feliz sorriso suor' },
      { char: '😂', k: 'feliz sorriso lagrimas chorando rindo' },
      { char: '🤣', k: 'feliz sorriso rolando chorando rindo' },
      { char: '🥲', k: 'feliz lagrima sorrindo chorando' },
      { char: '😊', k: 'feliz sorriso bochechas' },
      { char: '😇', k: 'feliz anjo' },
      { char: '🙂', k: 'feliz sorriso leve' },
      { char: '🙃', k: 'feliz sorriso invertido de cabeca para baixo' },
      { char: '😉', k: 'piscando olho' },
      { char: '😌', k: 'aliviado calmo' },
      { char: '😍', k: 'amor coracoes apaixonado' },
      { char: '🥰', k: 'amor coracoes apaixonado carinho' },
      { char: '😘', k: 'beijo amor coracao' },
      { char: '😗', k: 'beijo' },
      { char: '😙', k: 'beijo' },
      { char: '😚', k: 'beijo' },
      { char: '😋', k: 'delicia lingua comida' },
      { char: '😛', k: 'lingua' },
      { char: '😝', k: 'lingua' },
      { char: '😜', k: 'lingua piscando' },
      { char: '🤪', k: 'louco doido' },
      { char: '🤨', k: 'desconfiado sobrancelha' },
      { char: '🧐', k: 'monoculo serio inteligente' },
      { char: '🤓', k: 'nerd oculos estudioso' },
      { char: '😎', k: 'oculos escuros legal' },
      { char: '🥸', k: 'disfarce bigode' },
      { char: '🤩', k: 'estrela maravilhado' },
      { char: '🥳', k: 'festa comemoracao' },
      { char: '😏', k: 'malicioso sorriso' },
      { char: '😒', k: 'triste chateado irritado aborrecido' },
      { char: '😞', k: 'triste chateado decepcionado' },
      { char: '😔', k: 'triste pensativo' },
      { char: '😟', k: 'preocupado triste' },
      { char: '😕', k: 'confuso triste' },
      { char: '🙁', k: 'triste' },
      { char: '☹️', k: 'triste' },
      { char: '😣', k: 'triste' },
      { char: '😖', k: 'triste dor' },
      { char: '😫', k: 'triste cansaço' },
      { char: '😩', k: 'triste cansaço dor' },
      { char: '🥺', k: 'implorando triste fofo chorando' },
      { char: '😢', k: 'triste chorando lagrima' },
      { char: '😭', k: 'triste chorando muito' },
      { char: '😤', k: 'raiva bravo fumaca nariz' },
      { char: '😠', k: 'raiva bravo' },
      { char: '😡', k: 'raiva bravo vermelho' },
      { char: '🤬', k: 'raiva xingando palavrao' },
      { char: '🤯', k: 'cabeca explodindo surpresa choque' },
      { char: '😳', k: 'envergonhado surpreso vermelho' },
      { char: '🥵', k: 'calor suor vermelho' },
      { char: '🥶', k: 'frio gelo azul' },
      { char: '😱', k: 'susto medo panico surpresa' },
      { char: '😨', k: 'medo susto' },
      { char: '😰', k: 'medo suor azul' },
      { char: '😥', k: 'alivio suor' },
      { char: '😓', k: 'suor cansado' },
      { char: '🤗', k: 'abraco maos' },
      { char: '🤔', k: 'pensativo duvida' },
      { char: '🫣', k: 'escondido olho' },
      { char: '🤭', k: 'risadinha mao boca' },
      { char: '🥱', k: 'bocejo sono cansado' },
      { char: '🤫', k: 'silencio shhh' },
      { char: '🫠', k: 'derretendo calor' },
      { char: '🤥', k: 'mentiroso pinóquio nariz longo' },
      { char: '😶', k: 'sem boca mudo silencio' },
      { char: '😐', k: 'neutro serio' },
      { char: '😑', k: 'inexpressivo chateado' },
      { char: '😬', k: 'nervoso dentes' },
      { char: '🙄', k: 'olhos rolando tédio revirando' },
      { char: '😯', k: 'surpreso' },
      { char: '😦', k: 'surpreso boquiaberto' },
      { char: '😧', k: 'surpreso chocado' },
      { char: '😮', k: 'surpreso boca aberta' },
      { char: '😲', k: 'surpreso admirado' },
      { char: '😴', k: 'dormindo zzz sono' },
      { char: '🤤', k: 'babando fome' },
      { char: '😪', k: 'sono cansado' },
      { char: '😵', k: 'tonto' },
      { char: '🤐', k: 'ziper silencio' },
      { char: '🥴', k: 'bebado tonto' },
      { char: '🤢', k: 'enjoo nojo verde' },
      { char: '🤮', k: 'vomito nojo verde' },
      { char: '🤧', k: 'espirro doente' },
      { char: '😷', k: 'mascara doente medico' },
      { char: '🤒', k: 'doente termometro febre' },
      { char: '🤕', k: 'doente machucado faixa' },
      { char: '👋', k: 'tchau oi mao acenando' },
      { char: '🤚', k: 'mao levantada pare' },
      { char: '🖐️', k: 'mao espalmada pare' },
      { char: '✋', k: 'mao levantada' },
      { char: '🖖', k: 'spock star trek' },
      { char: '👌', k: 'ok perfeito legal' },
      { char: '🤌', k: 'mao italiana' },
      { char: '🤏', k: 'pouco pequeno beliscao' },
      { char: '✌️', k: 'paz vitoria dois' },
      { char: '🤞', k: 'dedos cruzados sorte' },
      { char: '🤟', k: 'te amo libras' },
      { char: '🤘', k: 'rock chifres' },
      { char: '🤙', k: 'telefone hang loose' },
      { char: '👈', k: 'esquerda dedo apontando' },
      { char: '👉', k: 'direita dedo apontando' },
      { char: '👆', k: 'cima dedo apontando' },
      { char: '👇', k: 'baixo dedo apontando' },
      { char: '☝️', k: 'um dedo apontando' },
      { char: '👍', k: 'joia curtir ok legal' },
      { char: '👎', k: 'reprovar nao ruim' },
      { char: '✊', k: 'punho resistencia' },
      { char: '👊', k: 'soco punho' },
      { char: '🤛', k: 'soco esquerda' },
      { char: '🤜', k: 'soco direita' },
      { char: '👏', k: 'palmas parabens bater' },
      { char: '🙌', k: 'celebracao levantando maos aleluia' },
      { char: '👐', k: 'maos abertas abraco' },
      { char: '🤲', k: 'maos juntas rezar' },
      { char: '🤝', k: 'aperto de mao acordo' },
      { char: '🙏', k: 'rezar oracao por favor amem' },
      { char: '👶', k: 'bebe crianca' },
      { char: '👦', k: 'menino garoto' },
      { char: '👧', k: 'menina garota' },
      { char: '👨', k: 'homem' },
      { char: '👩', k: 'mulher' },
      { char: '👴', k: 'idoso velho avo' },
      { char: '👵', k: 'idosa velha avo' },
      { char: '👮', k: 'policial' },
      { char: '👷', k: 'construtor engenheiro peao' },
      { char: '💂', k: 'guarda' },
      { char: '🕵️', k: 'detetive espiao investigacao' },
      { char: '👩‍⚕️', k: 'medica doutora enfermeira' },
      { char: '👨‍⚕️', k: 'medico doutor enfermeiro' },
      { char: '🎓', k: 'formatura escola chapeu' },
      { char: '🗣️', k: 'falando gritando pessoa' },
      { char: '👤', k: 'silhueta perfil pessoa' }
    ]
  },
  {
    id: 'animals',
    name: 'Animais e natureza',
    icon: '🐻',
    emojis: [
      { char: '🐶', k: 'cachorro cão' },
      { char: '🐱', k: 'gato' },
      { char: '🐭', k: 'rato' },
      { char: '🐹', k: 'hamster' },
      { char: '🐰', k: 'coelho' },
      { char: '🦊', k: 'raposa' },
      { char: '🐻', k: 'urso' },
      { char: '🐼', k: 'panda' },
      { char: '🐻‍❄️', k: 'urso polar' },
      { char: '🐨', k: 'coala' },
      { char: '🐯', k: 'tigre' },
      { char: '🦁', k: 'leao' },
      { char: '🐮', k: 'vaca' },
      { char: '🐷', k: 'porco' },
      { char: '🐸', k: 'sapo' },
      { char: '🐵', k: 'macaco' },
      { char: '🐔', k: 'galinha' },
      { char: '🐧', k: 'pinguim' },
      { char: '🐦', k: 'passaro' },
      { char: '🐤', k: 'pintinho' },
      { char: '🦆', k: 'pato' },
      { char: '🦅', k: 'aguia' },
      { char: '🦉', k: 'coruja' },
      { char: '🦇', k: 'morcego' },
      { char: '🐺', k: 'lobo' },
      { char: '🐗', k: 'javali' },
      { char: '🐴', k: 'cavalo' },
      { char: '🦄', k: 'unicornio' },
      { char: '🐝', k: 'abelha inseto' },
      { char: '🪱', k: 'minhoca verme' },
      { char: '🐛', k: 'lagarta' },
      { char: '🦋', k: 'borboleta' },
      { char: '🐌', k: 'caracol' },
      { char: '🐞', k: 'joaninha' },
      { char: '🐜', k: 'formiga' },
      { char: '🦟', k: 'mosquito pernilongo' },
      { char: '🕷️', k: 'aranha' },
      { char: '🦂', k: 'escorpiao' },
      { char: '🐢', k: 'tartaruga' },
      { char: '🐍', k: 'cobra serpente' },
      { char: '🦎', k: 'lagarto' },
      { char: '🦖', k: 'dinossauro trex' },
      { char: '🦕', k: 'dinossauro' },
      { char: '🐙', k: 'polvo' },
      { char: '🦑', k: 'lula' },
      { char: '🦐', k: 'camarao' },
      { char: '🦞', k: 'lagosta' },
      { char: '🦀', k: 'caranguejo' },
      { char: '🐡', k: 'peixe' },
      { char: '🐠', k: 'peixe' },
      { char: '🐟', k: 'peixe' },
      { char: '🐬', k: 'golfinho' },
      { char: '🐳', k: 'baleia' },
      { char: '🐋', k: 'baleia' },
      { char: '🦈', k: 'tubarao' },
      { char: '🐊', k: 'jacare crocodilo' },
      { char: '🐅', k: 'tigre' },
      { char: '🐆', k: 'onca leopardo' },
      { char: '🦓', k: 'zebra' },
      { char: '🦍', k: 'gorila' },
      { char: '🦧', k: 'orangotango' },
      { char: '🐘', k: 'elefante' },
      { char: '🦛', k: 'hipopotamo' },
      { char: '🦏', k: 'rinoceronte' },
      { char: '🐪', k: 'camelo' },
      { char: '🦒', k: 'girafa' },
      { char: '🦘', k: 'canguru' },
      { char: '🐃', k: 'bufalo' },
      { char: '🐂', k: 'boi' },
      { char: '🐄', k: 'vaca' },
      { char: '🐎', k: 'cavalo' },
      { char: '🐖', k: 'porco' },
      { char: '🐏', k: 'ovelha' },
      { char: '🐑', k: 'ovelha carneiro' },
      { char: '🦙', k: 'lhama' },
      { char: '🐐', k: 'bode cabra' },
      { char: '🦌', k: 'veado' },
      { char: '🐕', k: 'cachorro cao' },
      { char: '🐩', k: 'cachorro poodle' },
      { char: '🦮', k: 'cao guia' },
      { char: '🐕‍🦺', k: 'cao servico' },
      { char: '🐈', k: 'gato' },
      { char: '🐈‍⬛', k: 'gato preto' },
      { char: '🐓', k: 'galo' },
      { char: '🦃', k: 'peru' },
      { char: '🦚', k: 'pavao' },
      { char: '🦜', k: 'papagaio' },
      { char: '🦢', k: 'cisne' },
      { char: '🦩', k: 'flamingo' },
      { char: '🕊️', k: 'pomba paz' },
      { char: '🌿', k: 'planta folha' },
      { char: '🌱', k: 'planta semente' },
      { char: '🌲', k: 'arvore pinheiro' },
      { char: '🌳', k: 'arvore' },
      { char: '🌴', k: 'arvore palmeira' },
      { char: '🌵', k: 'cacto' },
      { char: '🌾', k: 'trigo planta' },
      { char: '🌷', k: 'flor tulipa' },
      { char: '🌹', k: 'flor rosa' },
      { char: '🌻', k: 'flor girassol' },
      { char: '🌼', k: 'flor margarida' },
      { char: '🌸', k: 'flor cerejeira sakura' },
      { char: '🌺', k: 'flor hibisco' },
      { char: '🍄', k: 'cogumelo' },
      { char: '🍁', k: 'folha outono' },
      { char: '🍂', k: 'folha seca' },
      { char: '🍃', k: 'folha voando' }
    ]
  },
  {
    id: 'food',
    name: 'Comidas e bebidas',
    icon: '🍔',
    emojis: [
      { char: '🍏', k: 'maca verde fruta' },
      { char: '🍎', k: 'maca vermelha fruta' },
      { char: '🍐', k: 'pera fruta' },
      { char: '🍊', k: 'laranja fruta' },
      { char: '🍋', k: 'limao fruta' },
      { char: '🍌', k: 'banana fruta' },
      { char: '🍉', k: 'melancia fruta' },
      { char: '🍇', k: 'uva fruta' },
      { char: '🍓', k: 'morango fruta' },
      { char: '🫐', k: 'mirtilo fruta' },
      { char: '🍈', k: 'melao fruta' },
      { char: '🍒', k: 'cereja fruta' },
      { char: '🍑', k: 'pessego fruta' },
      { char: '🥭', k: 'manga fruta' },
      { char: '🍍', k: 'abacaxi fruta' },
      { char: '🥥', k: 'coco fruta' },
      { char: '🥝', k: 'kiwi fruta' },
      { char: '🍅', k: 'tomate' },
      { char: '🥑', k: 'abacate' },
      { char: '🍆', k: 'berinjela' },
      { char: '🥔', k: 'batata' },
      { char: '🥕', k: 'cenoura' },
      { char: '🌽', k: 'milho' },
      { char: '🌶️', k: 'pimenta' },
      { char: '🫑', k: 'pimentao' },
      { char: '🥒', k: 'pepino' },
      { char: '🥬', k: 'alface verdura' },
      { char: '🥦', k: 'brocolis verdura' },
      { char: '🧄', k: 'alho' },
      { char: '🧅', k: 'cebola' },
      { char: '🍄', k: 'cogumelo' },
      { char: '🥜', k: 'amendoim' },
      { char: '🍞', k: 'pao' },
      { char: '🥐', k: 'croissant' },
      { char: '🥖', k: 'baguete pao' },
      { char: '🥨', k: 'pretzel' },
      { char: '🥯', k: 'bagel' },
      { char: '🥞', k: 'panqueca' },
      { char: '🧇', k: 'waffle' },
      { char: '🧀', k: 'queijo' },
      { char: '🍖', k: 'carne osso' },
      { char: '🍗', k: 'frango' },
      { char: '🥩', k: 'bife carne' },
      { char: '🥓', k: 'bacon' },
      { char: '🍔', k: 'hamburguer sanduiche' },
      { char: '🍟', k: 'batata frita' },
      { char: '🍕', k: 'pizza' },
      { char: '🌭', k: 'cachorro quente hotdog' },
      { char: '🥪', k: 'sanduiche' },
      { char: '🌮', k: 'taco' },
      { char: '🌯', k: 'burrito' },
      { char: '🥗', k: 'salada' },
      { char: '🍿', k: 'pipoca' },
      { char: '🧈', k: 'manteiga' },
      { char: '🧂', k: 'sal' },
      { char: '🥫', k: 'lata sopa molho' },
      { char: '🍱', k: 'bento lanche' },
      { char: '🍘', k: 'biscoito arroz' },
      { char: '🍙', k: 'onigiri arroz' },
      { char: '🍚', k: 'arroz' },
      { char: '🍛', k: 'curry prato' },
      { char: '🍜', k: 'macarrao lamen' },
      { char: '🍝', k: 'espaguete massa' },
      { char: '🍠', k: 'batata doce' },
      { char: '🍢', k: 'espetinho' },
      { char: '🍣', k: 'sushi peixe cru' },
      { char: '🍤', k: 'camarao frito' },
      { char: '🍥', k: 'bolo peixe' },
      { char: '🥮', k: 'bolo lua' },
      { char: '🍡', k: 'dango doce' },
      { char: '🥟', k: 'pastel dumpling' },
      { char: '🥠', k: 'biscoito sorte' },
      { char: '🥡', k: 'caixa chinesa comida' },
      { char: '🦀', k: 'caranguejo' },
      { char: '🦞', k: 'lagosta' },
      { char: '🦐', k: 'camarao' },
      { char: '🦑', k: 'lula' },
      { char: '🍦', k: 'sorvete casquinha' },
      { char: '🍧', k: 'raspadinha' },
      { char: '🍨', k: 'sorvete' },
      { char: '🍩', k: 'rosquinha donut' },
      { char: '🍪', k: 'biscoito cookie' },
      { char: '🎂', k: 'bolo aniversario' },
      { char: '🍰', k: 'fatia bolo' },
      { char: '🧁', k: 'cupcake' },
      { char: '🥧', k: 'torta' },
      { char: '🍫', k: 'chocolate' },
      { char: '🍬', k: 'bala doce' },
      { char: '🍭', k: 'pirulito' },
      { char: '🍮', k: 'pudim' },
      { char: '🍯', k: 'mel' },
      { char: '🍼', k: 'mamadeira leite' },
      { char: '🥛', k: 'copo leite' },
      { char: '☕', k: 'cafe xicara' },
      { char: '🫖', k: 'bule cha' },
      { char: '🍵', k: 'cha xicara' },
      { char: '🍶', k: 'saque' },
      { char: '🍾', k: 'champanhe garrafa' },
      { char: '🍷', k: 'vinho taca' },
      { char: '🍸', k: 'taca martini' },
      { char: '🍹', k: 'bebida tropical suco' },
      { char: '🍺', k: 'cerveja copo' },
      { char: '🍻', k: 'cervejas brinde' },
      { char: '🥂', k: 'brinde tacas' },
      { char: '🥃', k: 'copo uisque' },
      { char: '🥤', k: 'copo canudo refrigerante' },
      { char: '🧋', k: 'bubble tea boba' },
      { char: '🧃', k: 'suco caixinha' },
      { char: '🧉', k: 'mate chimarrao' },
      { char: '🧊', k: 'gelo' },
      { char: '🥢', k: 'hashi palitos' },
      { char: '🍽️', k: 'prato garfo faca' },
      { char: '🍴', k: 'garfo faca' },
      { char: '🥄', k: 'colher' },
      { char: '🔪', k: 'faca' }
    ]
  },
  {
    id: 'activities',
    name: 'Atividades',
    icon: '⚽',
    emojis: [
      { char: '⚽', k: 'futebol bola' },
      { char: '🏀', k: 'basquete bola' },
      { char: '🏈', k: 'futebol americano' },
      { char: '⚾', k: 'beisebol bola' },
      { char: '🥎', k: 'softbol bola' },
      { char: '🎾', k: 'tenis bola raquete' },
      { char: '🏐', k: 'volei bola' },
      { char: '🏉', k: 'rugby' },
      { char: '🥏', k: 'frisbee' },
      { char: '🎱', k: 'sinuca bilhar bola 8' },
      { char: '🪀', k: 'ioio' },
      { char: '🏓', k: 'ping pong tenis mesa' },
      { char: '🏸', k: 'badminton' },
      { char: '🏒', k: 'hoquei gelo' },
      { char: '🏑', k: 'hoquei grama' },
      { char: '🥍', k: 'lacrosse' },
      { char: '🏏', k: 'criquete' },
      { char: '🪃', k: 'bumerangue' },
      { char: '🥅', k: 'gol rede' },
      { char: '⛳', k: 'golfe bandeira' },
      { char: '🪁', k: 'pipa' },
      { char: '🏹', k: 'arco flecha' },
      { char: '🎣', k: 'pesca vara' },
      { char: '🤿', k: 'mergulho mascara' },
      { char: '🥊', k: 'boxe luva' },
      { char: '🥋', k: 'artes marciais quimono' },
      { char: '🎽', k: 'corrida camisa' },
      { char: '🛹', k: 'skate' },
      { char: '🛼', k: 'patins' },
      { char: '🛷', k: 'treno' },
      { char: '⛸️', k: 'patinacao gelo' },
      { char: '🎿', k: 'esqui' },
      { char: '⛷️', k: 'esquiador' },
      { char: '🏂', k: 'snowboard' },
      { char: '🏋️', k: 'peso academia' },
      { char: '🤼', k: 'luta' },
      { char: '🤸', k: 'ginastica acrobacia' },
      { char: '⛹️', k: 'basquete pessoa' },
      { char: '🤺', k: 'esgrima' },
      { char: '🤾', k: 'handebol' },
      { char: '🏌️', k: 'golfista' },
      { char: '🏇', k: 'cavalo corrida' },
      { char: '🧘', k: 'ioga meditacao' },
      { char: '🏄', k: 'surf surfista' },
      { char: '🏊', k: 'natacao nadador' },
      { char: '🤽', k: 'polo aquatico' },
      { char: '🚣', k: 'remo barco' },
      { char: '🧗', k: 'escalada' },
      { char: '🚵', k: 'bicicleta montanha' },
      { char: '🚴', k: 'bicicleta ciclista' },
      { char: '🏆', k: 'trofeu premio campeao' },
      { char: '🥇', k: 'medalha ouro primeiro' },
      { char: '🥈', k: 'medalha prata segundo' },
      { char: '🥉', k: 'medalha bronze terceiro' },
      { char: '🏅', k: 'medalha esportes' },
      { char: '🎖️', k: 'medalha militar' },
      { char: '🏵️', k: 'roseta' },
      { char: '🎗️', k: 'fita laco' },
      { char: '🎫', k: 'ingresso bilhete' },
      { char: '🎟️', k: 'ingresso' },
      { char: '🎪', k: 'circo tenda' },
      { char: '🤹', k: 'malabarista' },
      { char: '🎭', k: 'teatro mascaras' },
      { char: '🩰', k: 'bale sapatilha' },
      { char: '🎨', k: 'arte paleta pintura' },
      { char: '🎬', k: 'cinema claquete filme' },
      { char: '🎤', k: 'microfone cantar' },
      { char: '🎧', k: 'fone ouvido' },
      { char: '🎼', k: 'musica partitura' },
      { char: '🎹', k: 'teclado piano' },
      { char: '🥁', k: 'tambor bateria' },
      { char: '🎷', k: 'saxofone' },
      { char: '🎺', k: 'trompete' },
      { char: '🎸', k: 'guitarra violao' },
      { char: '🪕', k: 'banjo' },
      { char: '🎻', k: 'violino' },
      { char: '🎲', k: 'dado jogo' },
      { char: '♟️', k: 'xadrez' },
      { char: '🎯', k: 'alvo dardo' },
      { char: '🎳', k: 'boliche' },
      { char: '🎮', k: 'videogame controle' },
      { char: '🎰', k: 'caca niquel cassino' },
      { char: '🧩', k: 'quebra cabeca' }
    ]
  },
  {
    id: 'travel',
    name: 'Viagens e lugares',
    icon: '🚗',
    emojis: [
      { char: '🚗', k: 'carro automovel' },
      { char: '🚕', k: 'taxi' },
      { char: '🚙', k: 'carro suv' },
      { char: '🚌', k: 'onibus' },
      { char: '🚎', k: 'onibus eletrico' },
      { char: '🏎️', k: 'carro corrida formula 1' },
      { char: '🚓', k: 'policia viatura' },
      { char: '🚑', k: 'ambulancia' },
      { char: '🚒', k: 'bombeiro caminhao' },
      { char: '🚐', k: 'van' },
      { char: '🛻', k: 'caminhonete picape' },
      { char: '🚚', k: 'caminhao entrega' },
      { char: '🚛', k: 'caminhao carga carreta' },
      { char: '🚜', k: 'trator' },
      { char: '🦯', k: 'bengala cego' },
      { char: '🦽', k: 'cadeira rodas' },
      { char: '🦼', k: 'cadeira rodas motorizada' },
      { char: '🛴', k: 'patinete' },
      { char: '🚲', k: 'bicicleta' },
      { char: '🛵', k: 'moto scooter' },
      { char: '🏍️', k: 'motocicleta moto' },
      { char: '🛺', k: 'tuk tuk' },
      { char: '🚨', k: 'sirene policia alerta' },
      { char: '🚔', k: 'policia viatura aproximando' },
      { char: '🚍', k: 'onibus aproximando' },
      { char: '🚘', k: 'carro aproximando' },
      { char: '🚖', k: 'taxi aproximando' },
      { char: '🚡', k: 'teleferico bondinho' },
      { char: '🚠', k: 'teleferico montanha' },
      { char: '🚟', k: 'trem suspenso' },
      { char: '🚃', k: 'vagao trem' },
      { char: '🚋', k: 'bonde' },
      { char: '🚞', k: 'trem montanha' },
      { char: '🚝', k: 'monotrilho trem' },
      { char: '🚄', k: 'trem bala rapido' },
      { char: '🚅', k: 'trem bala frente' },
      { char: '🚈', k: 'trem leve' },
      { char: '🚂', k: 'locomotiva Maria Fumaca trem' },
      { char: '🚆', k: 'trem' },
      { char: '🚇', k: 'metro' },
      { char: '🚊', k: 'bonde eletrico' },
      { char: '🚉', k: 'estacao trem metro' },
      { char: '✈️', k: 'aviao' },
      { char: '🛫', k: 'aviao decolando' },
      { char: '🛬', k: 'aviao pousando' },
      { char: '🛩️', k: 'aviao pequeno' },
      { char: '💺', k: 'assento cadeira voo' },
      { char: '🛰️', k: 'satelite' },
      { char: '🚀', k: 'foguete espaco' },
      { char: '🛸', k: 'disco voador ovni' },
      { char: '🚁', k: 'helicoptero' },
      { char: '🛶', k: 'canoa' },
      { char: '⛵', k: 'barco vela' },
      { char: '🚤', k: 'lancha barco rapido' },
      { char: '🛥️', k: 'iate barco motor' },
      { char: '🛳️', k: 'navio passageiro cruzeiro' },
      { char: '⛴️', k: 'balsa' },
      { char: '🚢', k: 'navio' },
      { char: '⚓', k: 'ancora navio mar' },
      { char: '🪝', k: 'gancho' },
      { char: '⛽', k: 'posto gasolina combustivel' },
      { char: '🚧', k: 'construcao obra barricada' },
      { char: '🚦', k: 'semaforo transito' },
      { char: '🚥', k: 'semaforo horizontal' },
      { char: '🚏', k: 'ponto onibus parada' },
      { char: '🗺️', k: 'mapa mundo mapa' },
      { char: '🗿', k: 'estatua pedra moai' },
      { char: '🗽', k: 'estatua liberdade nova york' },
      { char: '🗼', k: 'torre toquio' },
      { char: '🏰', k: 'castelo' },
      { char: '🏯', k: 'castelo japones' },
      { char: '🏟️', k: 'estadio arena' },
      { char: '🎡', k: 'roda gigante parque' },
      { char: '🎢', k: 'montanha russa' },
      { char: '🎠', k: 'carrossel' },
      { char: '⛲', k: 'fonte agua' },
      { char: '⛱️', k: 'guarda sol praia' },
      { char: '🏖️', k: 'praia guarda sol' },
      { char: '🏝️', k: 'ilha deserta coqueiro' },
      { char: '🏜️', k: 'deserto' },
      { char: '🌋', k: 'vulcao' },
      { char: '⛰️', k: 'montanha' },
      { char: '🏔️', k: 'montanha neve' },
      { char: '🗻', k: 'monte fuji' },
      { char: '🏕️', k: 'acampamento barraca' },
      { char: '⛺', k: 'barraca' },
      { char: '🛖', k: 'cabana' },
      { char: '🏠', k: 'casa' },
      { char: '🏡', k: 'casa jardim' },
      { char: '🏘️', k: 'casas vila' },
      { char: '🏚️', k: 'casa abandonada velha' },
      { char: '🏗️', k: 'construcao predio guindaste' },
      { char: '🏭', k: 'fabrica industria' },
      { char: '🏢', k: 'predio comercial escritorio' },
      { char: '🏬', k: 'loja departamento shopping' },
      { char: '🏣', k: 'correio japones' },
      { char: '🏤', k: 'correio' },
      { char: '🏥', k: 'hospital medico' },
      { char: '🏦', k: 'banco dinheiro' },
      { char: '🏨', k: 'hotel' },
      { char: '🏪', k: 'loja conveniencia' },
      { char: '🏫', k: 'escola' },
      { char: '🏩', k: 'hotel amor' },
      { char: '💒', k: 'casamento igreja' },
      { char: '🏛️', k: 'predio classico museu' },
      { char: '⛪', k: 'igreja' },
      { char: '🕌', k: 'mesquita' },
      { char: '🛕', k: 'templo hindu' },
      { char: '🕍', k: 'sinagoga' },
      { char: '⛩️', k: 'santuario xintoista' },
      { char: '🕋', k: 'caaba' },
      { char: '🌅', k: 'nascer sol mar' },
      { char: '🌄', k: 'nascer sol montanha' },
      { char: '🌠', k: 'estrela cadente' },
      { char: '🎇', k: 'fogo artificio vela' },
      { char: '🎆', k: 'fogos artificio' },
      { char: '🌇', k: 'por sol predios' },
      { char: '🌆', k: 'cidade crepusculo' },
      { char: '🏙️', k: 'cidade predios dia' },
      { char: '🌃', k: 'noite cidade estrelas' },
      { char: '🌌', k: 'via lactea espaço' },
      { char: '🌉', k: 'ponte noite' },
      { char: '🌁', k: 'nevoeiro ponte' }
    ]
  },
  {
    id: 'objects',
    name: 'Objetos',
    icon: '💡',
    emojis: [
      { char: '⌚', k: 'relogio pulso' },
      { char: '📱', k: 'celular smartphone telefone' },
      { char: '📲', k: 'celular seta' },
      { char: '💻', k: 'notebook laptop computador' },
      { char: '⌨️', k: 'teclado' },
      { char: '🖥️', k: 'computador desktop tela monitor' },
      { char: '🖨️', k: 'impressora' },
      { char: '🖱️', k: 'mouse' },
      { char: '🖲️', k: 'trackball' },
      { char: '🕹️', k: 'joystick controle' },
      { char: '🗜️', k: 'morsa grampo' },
      { char: '💽', k: 'minidisc disco' },
      { char: '💾', k: 'disquete salvar' },
      { char: '💿', k: 'cd' },
      { char: '📀', k: 'dvd' },
      { char: '📼', k: 'fita vhs video' },
      { char: '📷', k: 'camera foto maquina' },
      { char: '📸', k: 'camera flash' },
      { char: '📹', k: 'camera video filmadora' },
      { char: '🎥', k: 'camera cinema' },
      { char: '📽️', k: 'projetor filme' },
      { char: '🎞️', k: 'rolo filme' },
      { char: '📞', k: 'telefone' },
      { char: '☎️', k: 'telefone fixo' },
      { char: '📟', k: 'pager bip' },
      { char: '📠', k: 'fax' },
      { char: '📺', k: 'televisao tv' },
      { char: '📻', k: 'radio' },
      { char: '🎙️', k: 'microfone estudio' },
      { char: '🎚️', k: 'controle volume' },
      { char: '🎛️', k: 'botoes controle' },
      { char: '🧭', k: 'bussola direcao' },
      { char: '⏱️', k: 'cronometro' },
      { char: '⏲️', k: 'timer' },
      { char: '⏰', k: 'despertador relogio alarme' },
      { char: '🕰️', k: 'relogio parede antigo' },
      { char: '⏳', k: 'ampulheta areia tempo caindo' },
      { char: '⌛', k: 'ampulheta areia tempo' },
      { char: '📡', k: 'antena satelite' },
      { char: '🔋', k: 'bateria pilha energia' },
      { char: '🔌', k: 'tomada energia plugue' },
      { char: '💡', k: 'lampada ideia luz' },
      { char: '🔦', k: 'lanterna luz' },
      { char: '🕯️', k: 'vela luz' },
      { char: '🪔', k: 'lampada oleo' },
      { char: '🧯', k: 'extintor incendio fogo' },
      { char: '🛢️', k: 'barril oleo petroleo' },
      { char: '💸', k: 'dinheiro voando' },
      { char: '💵', k: 'dinheiro dolar nota' },
      { char: '💴', k: 'dinheiro iene' },
      { char: '💶', k: 'dinheiro euro' },
      { char: '💷', k: 'dinheiro libra' },
      { char: '🪙', k: 'moeda dinheiro' },
      { char: '💰', k: 'saco dinheiro' },
      { char: '💳', k: 'cartao credito cartao' },
      { char: '💎', k: 'diamante joia pedra' },
      { char: '⚖️', k: 'balanca justica direito' },
      { char: '🪜', k: 'escada' },
      { char: '🧰', k: 'caixa ferramentas' },
      { char: '🪛', k: 'chave fenda' },
      { char: '🔧', k: 'chave inglesa ferramenta' },
      { char: '🔨', k: 'martelo ferramenta' },
      { char: '⚒️', k: 'martelo picareta ferramentas' },
      { char: '🛠️', k: 'ferramentas martelo chave' },
      { char: '⛏️', k: 'picareta mineracao' },
      { char: '🪚', k: 'serrote serra' },
      { char: '🔩', k: 'porca parafuso' },
      { char: '⚙️', k: 'engrenagem configuracao' },
      { char: '🪤', k: 'ratoeira' },
      { char: '🧱', k: 'tijolo parede' },
      { char: '⛓️', k: 'corrente' },
      { char: '🧲', k: 'ima magnetico' },
      { char: '🔫', k: 'arma pistola agua' },
      { char: '💣', k: 'bomba explosao' },
      { char: '🧨', k: 'dinamite foguete' },
      { char: '🪓', k: 'machado lenhador' },
      { char: '🔪', k: 'faca' },
      { char: '🗡️', k: 'adaga espada' },
      { char: '⚔️', k: 'espadas cruzadas' },
      { char: '🛡️', k: 'escudo defesa' },
      { char: '🚬', k: 'cigarro fumo' },
      { char: '⚰️', k: 'caixao funeral' },
      { char: '🪦', k: 'lapide tumulo' },
      { char: '⚱️', k: 'urna' },
      { char: '🏺', k: 'vaso anfora' },
      { char: '🔮', k: 'bola cristal magia vidente' },
      { char: '📿', k: 'rosario colar oracao' },
      { char: '🧿', k: 'olho grego mau olhado amuleto' },
      { char: '💈', k: 'barbearia poste barbearia' },
      { char: '⚗️', k: 'alambique quimica' },
      { char: '🔭', k: 'telescopio' },
      { char: '🔬', k: 'microscopio ciencia' },
      { char: '🕳️', k: 'buraco escuro' },
      { char: '🩹', k: 'curativo band-aid' },
      { char: '🩺', k: 'estetoscopio medico' },
      { char: '💊', k: 'pilula remedio medicamento' },
      { char: '💉', k: 'seringa vacina injeção' },
      { char: '🩸', k: 'gota sangue doacao' },
      { char: '🧬', k: 'dna genetica' },
      { char: '🦠', k: 'virus bacteria microbio' },
      { char: '🧫', k: 'placa petri ciencia' },
      { char: '🧪', k: 'tubo ensaio quimica' },
      { char: '🌡️', k: 'termometro temperatura calor' },
      { char: '🧹', k: 'vassoura limpeza' },
      { char: '🪠', k: 'desentupidor' },
      { char: '🧺', k: 'cesto roupa' },
      { char: '🧻', k: 'papel higienico' },
      { char: '🚽', k: 'privada vaso sanitario' },
      { char: '🚰', k: 'torneira agua' },
      { char: '🚿', k: 'chuveiro banho' },
      { char: '🛁', k: 'banheira' },
      { char: '🧼', k: 'sabonete lavar banho' },
      { char: '🪥', k: 'escova dentes' },
      { char: '🪒', k: 'barbeador lamina' },
      { char: '🧽', k: 'esponja lavar louca' },
      { char: '🪣', k: 'balde' },
      { char: '🧴', k: 'locao creme hidratante' },
      { char: '🛎️', k: 'sino hotel' },
      { char: '🔑', k: 'chave fechadura' },
      { char: '🗝️', k: 'chave antiga' },
      { char: '🚪', k: 'porta' },
      { char: '🪑', k: 'cadeira assento' },
      { char: '🛋️', k: 'sofa sala' },
      { char: '🛏️', k: 'cama dormir quarto' },
      { char: '🛌', k: 'pessoa cama dormir' },
      { char: '🧸', k: 'urso pelucia brinquedo' },
      { char: '🪆', k: 'matrioska boneca russa' },
      { char: '🖼️', k: 'quadro pintura arte moldura' },
      { char: '🪞', k: 'espelho reflexo' },
      { char: '🪟', k: 'janela' },
      { char: '🛍️', k: 'sacola compras loja' },
      { char: '🛒', k: 'carrinho compras supermercado' },
      { char: '🎁', k: 'presente surpresa caixa' },
      { char: '🎈', k: 'balao bexiga festa' },
      { char: '🎏', k: 'bandeira carpa peixe' },
      { char: '🎀', k: 'laco fita rosa' },
      { char: '🪄', k: 'varinha magica' },
      { char: '🪅', k: 'pinata festa' },
      { char: '🎊', k: 'confete festa' },
      { char: '🎉', k: 'festa confete comemoracao' },
      { char: '🎎', k: 'bonecas japonesas' },
      { char: '🏮', k: 'lanterna japonesa papel' },
      { char: '🎐', k: 'sino vento japones' },
      { char: '🧧', k: 'envelope vermelho sorte' },
      { char: '✉️', k: 'envelope carta email correio' },
      { char: '📩', k: 'envelope carta seta' },
      { char: '📨', k: 'envelope correio' },
      { char: '📧', k: 'email correio eletronico' },
      { char: '💌', k: 'carta amor coracao envelope' },
      { char: '📥', k: 'caixa entrada bandeja' },
      { char: '📤', k: 'caixa saida bandeja' },
      { char: '📦', k: 'caixa pacote correio encomenda' },
      { char: '🏷️', k: 'etiqueta tag' },
      { char: '🪧', k: 'placa manifestacao' },
      { char: '📪', k: 'caixa correio fechada' },
      { char: '📫', k: 'caixa correio aberta' },
      { char: '📬', k: 'caixa correio cheia' },
      { char: '📭', k: 'caixa correio vazia' },
      { char: '📮', k: 'caixa postal vermelha' },
      { char: '📯', k: 'corneta correio' },
      { char: '📜', k: 'pergaminho papel' },
      { char: '📃', k: 'pagina papel enrolada' },
      { char: '📄', k: 'pagina papel arquivo' },
      { char: '📑', k: 'marcadores papel' },
      { char: '🧾', k: 'recibo nota fiscal comprovante' },
      { char: '📊', k: 'grafico barras' },
      { char: '📈', k: 'grafico subindo crescimento' },
      { char: '📉', k: 'grafico caindo queda' },
      { char: '🗒️', k: 'bloco espiral' },
      { char: '🗓️', k: 'calendario espiral data' },
      { char: '📆', k: 'calendario arrancar' },
      { char: '📅', k: 'calendario data evento' },
      { char: '🗑️', k: 'lixo lixeira' },
      { char: '📇', k: 'arquivos cartoes' },
      { char: '🗃️', k: 'caixa arquivos' },
      { char: '🗳️', k: 'urna votacao' },
      { char: '🗄️', k: 'armario arquivos gavetas' },
      { char: '📋', k: 'prancheta area transferencia' },
      { char: '📁', k: 'pasta arquivos' },
      { char: '📂', k: 'pasta aberta arquivos' },
      { char: '🗂️', k: 'divisores pasta' },
      { char: '🗞️', k: 'jornal enrolado noticia' },
      { char: '📰', k: 'jornal noticia' },
      { char: '📓', k: 'caderno preto' },
      { char: '📔', k: 'caderno decorado' },
      { char: '📒', k: 'caderno amarelo' },
      { char: '📕', k: 'livro fechado vermelho' },
      { char: '📗', k: 'livro verde' },
      { char: '📘', k: 'livro azul' },
      { char: '📙', k: 'livro laranja' },
      { char: '📚', k: 'livros biblioteca pilha' },
      { char: '📖', k: 'livro aberto leitura ler' },
      { char: '🔖', k: 'marcador pagina' },
      { char: '🧷', k: 'alfinete seguranca' },
      { char: '🔗', k: 'link corrente elo conexao' },
      { char: '📎', k: 'clipe papel anexo' },
      { char: '🖇️', k: 'clipes papel' },
      { char: '📐', k: 'esquadro triangulo regua' },
      { char: '📏', k: 'regua' },
      { char: '🧮', k: 'abaco calculo matematica' },
      { char: '📌', k: 'tachinha pino' },
      { char: '📍', k: 'pino mapa localizacao' },
      { char: '✂️', k: 'tesoura' },
      { char: '🖊️', k: 'caneta' },
      { char: '🖋️', k: 'caneta tinteiro' },
      { char: '✒️', k: 'pena' },
      { char: '🖌️', k: 'pincel' },
      { char: '🖍️', k: 'giz cera' },
      { char: '📝', k: 'bloco notas escrever caneta' },
      { char: '✏️', k: 'lapis' },
      { char: '🔍', k: 'lupa pesquisa buscar' },
      { char: '🔎', k: 'lupa direita pesquisa' },
      { char: '🔏', k: 'cadeado caneta seguranca' },
      { char: '🔐', k: 'cadeado chave fechado' },
      { char: '🔒', k: 'cadeado trancado seguro fechado' },
      { char: '🔓', k: 'cadeado destrancado aberto' }
    ]
  },
  {
    id: 'symbols',
    name: 'Símbolos',
    icon: '🎶',
    emojis: [
      { char: '❤️', k: 'coracao vermelho amor' },
      { char: '🧡', k: 'coracao laranja' },
      { char: '💛', k: 'coracao amarelo' },
      { char: '💚', k: 'coracao verde' },
      { char: '💙', k: 'coracao azul' },
      { char: '💜', k: 'coracao roxo' },
      { char: '🖤', k: 'coracao preto' },
      { char: '🤍', k: 'coracao branco' },
      { char: '🤎', k: 'coracao marrom' },
      { char: '💔', k: 'coracao partido triste amor' },
      { char: '❣️', k: 'exclamacao coracao' },
      { char: '💕', k: 'dois coracoes amor' },
      { char: '💞', k: 'coracoes girando amor' },
      { char: '💓', k: 'coracao batendo amor' },
      { char: '💗', k: 'coracao crescendo amor' },
      { char: '💖', k: 'coracao brilhante amor' },
      { char: '💘', k: 'coracao flecha cupido' },
      { char: '💝', k: 'coracao fita presente' },
      { char: '💟', k: 'decoracao coracao' },
      { char: '☮️', k: 'paz' },
      { char: '✝️', k: 'cruz religiao cristao' },
      { char: '☪️', k: 'lua estrela islã' },
      { char: '🕉️', k: 'om hinduísmo' },
      { char: '☸️', k: 'roda dharma budismo' },
      { char: '✡️', k: 'estrela davi judaismo' },
      { char: '🔯', k: 'estrela seis pontas ponto' },
      { char: '🕎', k: 'menora' },
      { char: '☯️', k: 'yin yang' },
      { char: '☦️', k: 'cruz ortodoxa' },
      { char: '🛐', k: 'local culto' },
      { char: '⛎', k: 'serpentario' },
      { char: '♈', k: 'aries signo' },
      { char: '♉', k: 'touro signo' },
      { char: '♊', k: 'gemeos signo' },
      { char: '♋', k: 'cancer signo' },
      { char: '♌', k: 'leao signo' },
      { char: '♍', k: 'virgem signo' },
      { char: '♎', k: 'libra signo' },
      { char: '♏', k: 'escorpiao signo' },
      { char: '♐', k: 'sagitario signo' },
      { char: '♑', k: 'capricornio signo' },
      { char: '♒', k: 'aquario signo' },
      { char: '♓', k: 'peixes signo' },
      { char: '🆔', k: 'id identidade' },
      { char: '⚛️', k: 'atomo ciencia quimica fisica' },
      { char: '🉑', k: 'ideograma japones aceitavel' },
      { char: '☢️', k: 'radioativo perigo' },
      { char: '☣️', k: 'risco biologico perigo' },
      { char: '📴', k: 'telefone desligado celular' },
      { char: '📳', k: 'modo vibracao celular' },
      { char: '🈶', k: 'ideograma japones existir' },
      { char: '🈚', k: 'ideograma japones nao existir' },
      { char: '🈸', k: 'ideograma japones aplicacao' },
      { char: '🈺', k: 'ideograma japones aberto negocio' },
      { char: '🈷️', k: 'ideograma japones mes' },
      { char: '✴️', k: 'estrela oito pontas' },
      { char: '🆚', k: 'versus contra luta vs' },
      { char: '💮', k: 'flor branca' },
      { char: '🉐', k: 'ideograma japones ganho' },
      { char: '㊙️', k: 'ideograma japones segredo' },
      { char: '㊗️', k: 'ideograma japones parabens' },
      { char: '🈴', k: 'ideograma japones uniao aprovado' },
      { char: '🈵', k: 'ideograma japones lotado' },
      { char: '🈹', k: 'ideograma japones desconto' },
      { char: '🈲', k: 'ideograma japones proibido' },
      { char: '🅰️', k: 'a sangue tipo letra' },
      { char: '🅱️', k: 'b sangue tipo letra' },
      { char: '🆎', k: 'ab sangue tipo letras' },
      { char: '🆑', k: 'cl limpar' },
      { char: '🅾️', k: 'o sangue tipo letra' },
      { char: '🆘', k: 'sos socorro ajuda' },
      { char: '❌', k: 'x erro fechar errado' },
      { char: '⭕', k: 'circulo o vazio' },
      { char: '🛑', k: 'pare placa vermelho stop' },
      { char: '⛔', k: 'entrada proibida transito' },
      { char: '📛', k: 'cracha nome' },
      { char: '🚫', k: 'proibido nao bloqueado' },
      { char: '💯', k: 'cem pontos nota 100 maximo' },
      { char: '💢', k: 'raiva veia estressado' },
      { char: '♨️', k: 'fontes termais quentes' },
      { char: '🚷', k: 'proibido pedestres' },
      { char: '🚯', k: 'proibido lixo' },
      { char: '🚳', k: 'proibido bicicletas' },
      { char: '🚱', k: 'agua nao potavel proibido' },
      { char: '🔞', k: 'maiores 18 proibido menores dezoito' },
      { char: '📵', k: 'proibido celular telefones' },
      { char: '🚭', k: 'proibido fumar cigarro' },
      { char: '❗', k: 'exclamacao atencao vermelho' },
      { char: '❕', k: 'exclamacao branca' },
      { char: '❓', k: 'interrogacao pergunta vermelho duvida' },
      { char: '❔', k: 'interrogacao branca duvida' },
      { char: '‼️', k: 'dupla exclamacao' },
      { char: '⁉️', k: 'exclamacao interrogacao' },
      { char: '🔅', k: 'brilho baixo sol' },
      { char: '🔆', k: 'brilho alto sol' },
      { char: '〽️', k: 'marca cantores japoneses alternancia partitura' },
      { char: '⚠️', k: 'aviso perigo atencao amarelo alerta' },
      { char: '🚸', k: 'criancas atravessando escola' },
      { char: '🔱', k: 'tridente' },
      { char: '⚜️', k: 'flor lis' },
      { char: '🔰', k: 'simbolo principiante folha' },
      { char: '♻️', k: 'reciclagem verde' },
      { char: '✅', k: 'check verde certo ok confirmar' },
      { char: '🈯', k: 'ideograma japones reservado' },
      { char: '💹', k: 'grafico subindo iene' },
      { char: '❇️', k: 'brilho verde' },
      { char: '✳️', k: 'asterisco verde' },
      { char: '❎', k: 'x verde botao cruz' },
      { char: '🌐', k: 'globo meridianos internet' },
      { char: '💠', k: 'losango ponto' },
      { char: 'Ⓜ️', k: 'm circulo metro' },
      { char: '🌀', k: 'ciclone furacao espiral' },
      { char: '💤', k: 'zzz sono dormir' },
      { char: '🏧', k: 'caixa eletronico dinheiro' },
      { char: '🚾', k: 'wc banheiro' },
      { char: '♿', k: 'cadeirante deficiente acesso' },
      { char: '🅿️', k: 'estacionamento p' },
      { char: '🛗', k: 'elevador' },
      { char: '🈳', k: 'ideograma japones vazio' },
      { char: '🈂️', k: 'ideograma japones servico' },
      { char: '🛂', k: 'controle passaportes' },
      { char: '🛃', k: 'alfandega' },
      { char: '🛄', k: 'restituicao bagagem mala' },
      { char: '🛅', k: 'guarda volumes mala' },
      { char: '🚹', k: 'banheiro masculino homem' },
      { char: '🚺', k: 'banheiro feminino mulher' },
      { char: '🚼', k: 'bercario bebe fralda' },
      { char: '⚧️', k: 'transgenero' },
      { char: '🚻', k: 'banheiro unissex publico' },
      { char: '🚮', k: 'lixo jogue fora' },
      { char: '🎦', k: 'cinema filme tela' },
      { char: '📶', k: 'sinal wifi conexao barras' },
      { char: '🈁', k: 'ideograma japones aqui' },
      { char: '🔣', k: 'simbolos caracteres' },
      { char: 'ℹ️', k: 'informacao i info' },
      { char: '🔤', k: 'letras abc latinas' },
      { char: '🔡', k: 'letras abcd minusculas' },
      { char: '🔠', k: 'letras abcd maiusculas' },
      { char: '🆖', k: 'ng erro nao bom' },
      { char: '🆗', k: 'ok certo botao' },
      { char: '🆙', k: 'up cima' },
      { char: '🆒', k: 'cool legal' },
      { char: '🆕', k: 'new novo' },
      { char: '🆓', k: 'free gratis livre' },
      { char: '0️⃣', k: 'zero numero 0' },
      { char: '1️⃣', k: 'um numero 1' },
      { char: '2️⃣', k: 'dois numero 2' },
      { char: '3️⃣', k: 'tres numero 3' },
      { char: '4️⃣', k: 'quatro numero 4' },
      { char: '5️⃣', k: 'cinco numero 5' },
      { char: '6️⃣', k: 'seis numero 6' },
      { char: '7️⃣', k: 'sete numero 7' },
      { char: '8️⃣', k: 'oito numero 8' },
      { char: '9️⃣', k: 'nove numero 9' },
      { char: '🔟', k: 'dez numero 10' },
      { char: '🔢', k: 'numeros 1234' },
      { char: '#️⃣', k: 'hashtag jogo velha' },
      { char: '*️⃣', k: 'asterisco estrela' },
      { char: '⏏️', k: 'ejetar botao' },
      { char: '▶️', k: 'reproduzir play seta' },
      { char: '⏸️', k: 'pausar' },
      { char: '⏯️', k: 'reproduzir pausar' },
      { char: '⏹️', k: 'parar stop' },
      { char: '⏺️', k: 'gravar bolinha' },
      { char: '⏭️', k: 'proxima faixa' },
      { char: '⏮️', k: 'faixa anterior' },
      { char: '⏩', k: 'avanco rapido' },
      { char: '⏪', k: 'retrocesso rapido' },
      { char: '⏫', k: 'seta dupla cima' },
      { char: '⏬', k: 'seta dupla baixo' },
      { char: '◀️', k: 'seta esquerda play' },
      { char: '🔼', k: 'seta cima play' },
      { char: '🔽', k: 'seta baixo play' },
      { char: '➡️', k: 'seta direita direcao' },
      { char: '⬅️', k: 'seta esquerda direcao' },
      { char: '⬆️', k: 'seta cima direcao' },
      { char: '⬇️', k: 'seta baixo direcao' },
      { char: '↗️', k: 'seta diagonal cima direita' },
      { char: '↘️', k: 'seta diagonal baixo direita' },
      { char: '↙️', k: 'seta diagonal baixo esquerda' },
      { char: '↖️', k: 'seta diagonal cima esquerda' },
      { char: '↕️', k: 'seta cima baixo' },
      { char: '↔️', k: 'seta esquerda direita' },
      { char: '↪️', k: 'seta direita curvada' },
      { char: '↩️', k: 'seta esquerda curvada voltar' },
      { char: '⤴️', k: 'seta cima curvada' },
      { char: '⤵️', k: 'seta baixo curvada' },
      { char: '🔀', k: 'setas cruzadas embaralhar aleatorio' },
      { char: '🔁', k: 'repetir setas circulo' },
      { char: '🔂', k: 'repetir uma vez 1' },
      { char: '🔄', k: 'atualizar setas circulo recarregar giro' },
      { char: '🔃', k: 'recarregar setas verticais giro' },
      { char: '🎵', k: 'nota musical musica' },
      { char: '🎶', k: 'notas musicais musica' },
      { char: '➕', k: 'mais adicao positivo soma matematica' },
      { char: '➖', k: 'menos subtracao negativo matematica' },
      { char: '➗', k: 'divisao matematica' },
      { char: '✖️', k: 'vezes multiplicacao x matematica' },
      { char: '♾️', k: 'infinito para sempre' },
      { char: '💲', k: 'cifrao dolar dinheiro preco' },
      { char: '💱', k: 'cambio moeda conversao dinheiro' },
      { char: '™️', k: 'marca registrada tm' },
      { char: '©️', k: 'copyright direitos autorais c' },
      { char: '®️', k: 'marca registrada r' },
      { char: '〰️', k: 'linha ondulada onda' },
      { char: '➰', k: 'laco loop curl' },
      { char: '➿', k: 'laco duplo loop' },
      { char: '✔️', k: 'check marca verificacao ok certo' },
      { char: '☑️', k: 'check caixa verificacao ok certo' }
    ]
  },
  {
    id: 'flags',
    name: 'Bandeiras',
    icon: '🎌',
    emojis: [
      { char: '🎌', k: 'bandeiras cruzadas japao' },
      { char: '🏁', k: 'bandeira quadriculada corrida chegada' },
      { char: '🚩', k: 'bandeira vermelha perigo' },
      { char: '🏳️', k: 'bandeira branca rendicao paz' },
      { char: '🏳️‍🌈', k: 'bandeira arco iris lgbt orgulho' },
      { char: '🏴‍☠️', k: 'bandeira pirata caveira' },
      { char: '🇧🇷', k: 'bandeira brasil br' },
      { char: '🇺🇸', k: 'bandeira estados unidos eua usa' },
      { char: '🇬🇧', k: 'bandeira reino unido inglaterra uk' },
      { char: '🇫🇷', k: 'bandeira franca fr' },
      { char: '🇩🇪', k: 'bandeira alemanha de' },
      { char: '🇮🇹', k: 'bandeira italia it' },
      { char: '🇪🇸', k: 'bandeira espanha es' },
      { char: '🇵🇹', k: 'bandeira portugal pt' },
      { char: '🇯🇵', k: 'bandeira japao jp' },
      { char: '🇨🇳', k: 'bandeira china cn' },
      { char: '🇷🇺', k: 'bandeira russia ru' },
      { char: '🇦🇷', k: 'bandeira argentina ar' },
      { char: '🇲🇽', k: 'bandeira mexico mx' },
      { char: '🇨🇦', k: 'bandeira canada ca' }
    ]
  }
];

